# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# IP: ip/imem_ip/imem_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imem_ip || ORIG_REF_NAME==imem_ip} -quiet] -quiet
