# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/95223/Desktop/course_design/course_design.cache/wt [current_project]
set_property parent.project_path C:/Users/95223/Desktop/course_design/course_design.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/95223/Desktop/course_design/course_design.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/95223/Desktop/test_cross_compile/BOOT.coe
add_files C:/Users/95223/Desktop/test_cross_compile/cross_compile_ok_1210/BOOT.coe
read_verilog -library xil_defaultlib {
  C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/new/complete_inst_cpu/defines.v
  C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/new/complete_inst_cpu/LLbit_reg.v
  C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/new/SD_soft.v
  C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/new/complete_inst_cpu/cp0_reg.v
  C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/new/complete_inst_cpu/ctrl.v
  C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/new/complete_inst_cpu/data_ram.v
  C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/new/complete_inst_cpu/div.v
  C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/new/complete_inst_cpu/ex.v
  C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/new/complete_inst_cpu/ex_mem.v
  C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/new/complete_inst_cpu/hilo_reg.v
  C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/new/complete_inst_cpu/id.v
  C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/new/complete_inst_cpu/id_ex.v
  C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/new/complete_inst_cpu/if_id.v
  C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/new/complete_inst_cpu/mem.v
  C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/new/complete_inst_cpu/mem_wb.v
  C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/new/complete_inst_cpu/openmips.v
  C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/new/complete_inst_cpu/pc_reg.v
  C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/new/complete_inst_cpu/regfile.v
  C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/new/seg7.v
  C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/new/seg7x16.v
  C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/new/complete_inst_cpu/openmips_min_sopc.v
}
read_ip -quiet C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/ip/imem_ip/imem_ip.xci
set_property used_in_implementation false [get_files -all c:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/ip/imem_ip/imem_ip_ooc.xdc]

read_ip -quiet C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/ip/ip_iram_dual_port/ip_iram_dual_port.xci
set_property used_in_implementation false [get_files -all c:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/ip/ip_iram_dual_port/ip_iram_dual_port_ooc.xdc]

read_ip -quiet C:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all c:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/95223/Desktop/course_design/course_design.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files C:/Users/95223/Desktop/course_design/course_design.srcs/constrs_1/new/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top openmips_min_sopc -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef openmips_min_sopc.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file openmips_min_sopc_utilization_synth.rpt -pb openmips_min_sopc_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
