# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/ip/ip_iram_dual_port/ip_iram_dual_port.xci
# IP: The module: 'ip_iram_dual_port' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/ip/ip_iram_dual_port/ip_iram_dual_port_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_iram_dual_port'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/ip/ip_iram_dual_port/ip_iram_dual_port.xci
# IP: The module: 'ip_iram_dual_port' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/95223/Desktop/course_design/course_design.srcs/sources_1/ip/ip_iram_dual_port/ip_iram_dual_port_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_iram_dual_port'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
