######################################################################
#
# File name : openmips_min_sopc_tb_compile.do
# Created on: Thu Dec 12 00:02:17 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../course_design.srcs/sources_1/new/ddr_module" "+incdir+../../../../course_design.srcs/sources_1/ip/clk_wiz_1" \
"../../../../course_design.srcs/sources_1/ip/ip_iram_dual_port/sim/ip_iram_dual_port.v" \
"../../../../course_design.srcs/sources_1/ip/imem_ip/sim/imem_ip.v" \
"../../../../course_design.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_clk_wiz.v" \
"../../../../course_design.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.v" \
"../../../../course_design.srcs/sources_1/new/complete_inst_cpu/LLbit_reg.v" \
"../../../../course_design.srcs/sources_1/new/SD_soft.v" \
"../../../../course_design.srcs/sources_1/new/complete_inst_cpu/cp0_reg.v" \
"../../../../course_design.srcs/sources_1/new/complete_inst_cpu/ctrl.v" \
"../../../../course_design.srcs/sources_1/new/complete_inst_cpu/data_ram.v" \
"../../../../course_design.srcs/sources_1/new/complete_inst_cpu/div.v" \
"../../../../course_design.srcs/sources_1/new/complete_inst_cpu/ex.v" \
"../../../../course_design.srcs/sources_1/new/complete_inst_cpu/ex_mem.v" \
"../../../../course_design.srcs/sources_1/new/complete_inst_cpu/hilo_reg.v" \
"../../../../course_design.srcs/sources_1/new/complete_inst_cpu/id.v" \
"../../../../course_design.srcs/sources_1/new/complete_inst_cpu/id_ex.v" \
"../../../../course_design.srcs/sources_1/new/complete_inst_cpu/if_id.v" \
"../../../../course_design.srcs/sources_1/new/complete_inst_cpu/mem.v" \
"../../../../course_design.srcs/sources_1/new/complete_inst_cpu/mem_wb.v" \
"../../../../course_design.srcs/sources_1/new/complete_inst_cpu/openmips.v" \
"../../../../course_design.srcs/sources_1/new/complete_inst_cpu/openmips_min_sopc.v" \
"../../../../course_design.srcs/sources_1/new/complete_inst_cpu/pc_reg.v" \
"../../../../course_design.srcs/sources_1/new/complete_inst_cpu/regfile.v" \
"../../../../course_design.srcs/sources_1/new/seg7.v" \
"../../../../course_design.srcs/sources_1/new/seg7x16.v" \
"../../../../course_design.srcs/sources_1/new/complete_inst_cpu/openmips_min_sopc_tb.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

