######################################################################
#
# File name : openmips_min_sopc_tb.udo
# Created on: Sat Dec 07 12:06:53 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
