######################################################################
#
# File name : openmips_min_sopc_tb_wave.do
# Created on: Sat Dec 07 12:06:53 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
